server:
  port: 8000


spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        dialect=org:
          hibernate:
            ddl-auto: update
            dialect:
              MySQL5InnoDBDialect:nd
            show-sql: true